CREATE TABLE PRODUCTOS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR NOT NULL,
	DESCRIPCION VARCHAR NOT NULL,
	PRECIOBASE DECIMAL NOT NULL,
	TASAIMPUESTOS DECIMAL NOT NULL,
	ESTADO VARCHAR NOT NULL,
	CANTINVE INT NOT NULL
	);